package io.melan.npulab.tokenizer

import java.io.File
import java.util.regex.Pattern

/**
 * CLIP BPE tokenizer compatible with the vocab.json + merges.txt files shipped
 * by Hugging Face for `openai/clip-vit-large-patch14` — the text conditioning
 * tokenizer of Stable Diffusion 1.5 (77 tokens, BOS + text + EOS + padding).
 *
 * Mirrors openai/CLIP `simple_tokenizer.py`:
 *   1. whitespace-clean + lowercase;
 *   2. pre-tokenize with the CLIP regex (contractions / letter runs / single
 *      digits / punctuation runs — so "cat," splits into "cat" + ",");
 *   3. map each token's UTF-8 bytes through the GPT-2 byte→unicode table
 *      (this is what makes ANY input — Cyrillic, emoji — tokenizable: every
 *      possible byte exists in the vocab, so nothing falls back to <unk>);
 *   4. BPE-merge with ranks from merges.txt, last piece carries "</w>".
 *
 * Verified against HF `CLIPTokenizer` outputs in ClipTokenizerTest (fixtures
 * generated by transformers, incl. punctuation / Cyrillic / emoji prompts).
 */
class ClipTokenizer(vocabFile: File, mergesFile: File) {

    private val vocab: Map<String, Int>
    private val ranks: Map<Pair<String, String>, Int>
    private val bosId: Int
    private val eosId: Int
    private val unkId: Int
    private val bpeCache = HashMap<String, List<Int>>()

    init {
        vocab = parseVocab(vocabFile.readText())
        ranks = mergesFile.readLines()
            .drop(1)                                  // first line is "#version: 0.2"
            .filter { it.isNotBlank() && !it.startsWith("#") }
            .mapIndexed { idx, line ->
                val parts = line.trim().split(' ')
                (parts[0] to parts[1]) to idx
            }
            .toMap()
        bosId = vocab["<|startoftext|>"] ?: error("vocab missing <|startoftext|>")
        eosId = vocab["<|endoftext|>"] ?: error("vocab missing <|endoftext|>")
        unkId = eosId                                // CLIP uses EOS as unk
    }

    /** Encode `prompt` to a fixed-length 77-token id sequence with BOS/EOS/padding. */
    fun encode(prompt: String, maxLength: Int = 77): IntArray {
        val pieces = ArrayList<Int>()
        val matcher = CLIP_PATTERN.matcher(whitespaceClean(prompt).lowercase())
        while (matcher.find()) {
            pieces += bpe(matcher.group())
        }
        // HF truncation: keep the first (maxLength-2) content tokens, then EOS;
        // pad the tail with EOS (the SD 1.5 tokenizer's pad token).
        val content = if (pieces.size > maxLength - 2) pieces.subList(0, maxLength - 2) else pieces
        val ids = IntArray(maxLength) { eosId }
        ids[0] = bosId
        for (i in content.indices) ids[i + 1] = content[i]
        // ids[content.size + 1] is already eosId via the fill above.
        return ids
    }

    private fun whitespaceClean(s: String): String = s.replace(Regex("\\s+"), " ").trim()

    /** BPE for one pre-token. Returns vocab ids of the merged pieces. */
    private fun bpe(token: String): List<Int> {
        bpeCache[token]?.let { return it }
        // Special tokens pass through whole (they're in the vocab verbatim).
        vocab[token]?.takeIf { token.startsWith("<|") && token.endsWith("|>") }?.let {
            val r = listOf(it)
            bpeCache[token] = r
            return r
        }

        // UTF-8 bytes → printable unicode alphabet used by the vocab.
        val mapped = StringBuilder()
        for (b in token.toByteArray(Charsets.UTF_8)) {
            mapped.append(BYTE_ENCODER[b.toInt() and 0xFF])
        }
        if (mapped.isEmpty()) return emptyList()

        var pieces = ArrayList<String>(mapped.length)
        for (c in mapped) pieces.add(c.toString())
        pieces[pieces.size - 1] = pieces.last() + "</w>"

        while (pieces.size > 1) {
            var bestRank = Int.MAX_VALUE
            var first = ""
            var second = ""
            for (i in 0 until pieces.size - 1) {
                val r = ranks[pieces[i] to pieces[i + 1]] ?: continue
                if (r < bestRank) {
                    bestRank = r
                    first = pieces[i]
                    second = pieces[i + 1]
                }
            }
            if (bestRank == Int.MAX_VALUE) break
            // Merge ALL left-to-right occurrences of the best pair in one pass
            // (BPE semantics, matches openai's bpe()) — matters for repeats.
            val next = ArrayList<String>(pieces.size)
            var i = 0
            while (i < pieces.size) {
                if (i < pieces.size - 1 && pieces[i] == first && pieces[i + 1] == second) {
                    next.add(first + second)
                    i += 2
                } else {
                    next.add(pieces[i])
                    i += 1
                }
            }
            pieces = next
        }
        val result = pieces.map { vocab[it] ?: unkId }
        bpeCache[token] = result
        return result
    }

    private fun parseVocab(json: String): Map<String, Int> {
        // Hand-rolled parser to avoid pulling in a full JSON dependency for one file.
        // vocab.json is a flat {"token": id, ...} dict with string keys / int values.
        val out = HashMap<String, Int>(50_000)
        var i = json.indexOf('{')
        if (i < 0) error("vocab.json: missing {")
        i++
        while (i < json.length) {
            while (i < json.length && (json[i].isWhitespace() || json[i] == ',')) i++
            if (i >= json.length || json[i] == '}') break
            require(json[i] == '"') { "vocab.json: expected string key at $i" }
            i++
            val keyStart = i
            val keyBuilder = StringBuilder()
            while (i < json.length && json[i] != '"') {
                if (json[i] == '\\') {
                    when (val c = json[i + 1]) {
                        '"', '\\', '/' -> { keyBuilder.append(c); i += 2 }
                        'n' -> { keyBuilder.append('\n'); i += 2 }
                        't' -> { keyBuilder.append('\t'); i += 2 }
                        'u' -> {
                            val cp = json.substring(i + 2, i + 6).toInt(16)
                            keyBuilder.append(cp.toChar())
                            i += 6
                        }
                        else -> { keyBuilder.append(c); i += 2 }
                    }
                } else {
                    keyBuilder.append(json[i]); i++
                }
            }
            require(i < json.length) { "vocab.json: unterminated string starting at $keyStart" }
            i++ // closing quote
            while (i < json.length && (json[i].isWhitespace() || json[i] == ':')) i++
            val numStart = i
            while (i < json.length && (json[i].isDigit() || json[i] == '-')) i++
            val id = json.substring(numStart, i).toInt()
            out[keyBuilder.toString()] = id
        }
        return out
    }

    companion object {
        /**
         * openai/CLIP pre-tokenization pattern. Order matters: special tokens,
         * English contractions, letter runs, single digits, punctuation runs.
         */
        private val CLIP_PATTERN: Pattern = Pattern.compile(
            "<\\|startoftext\\|>|<\\|endoftext\\|>|'s|'t|'re|'ve|'m|'ll|'d|" +
                "[\\p{L}]+|[\\p{N}]|[^\\s\\p{L}\\p{N}]+",
            Pattern.CASE_INSENSITIVE or Pattern.UNICODE_CASE,
        )

        /**
         * GPT-2 byte→unicode table: printable bytes map to themselves, the rest
         * shift into 0x100+ so every byte is a visible, vocab-representable char.
         */
        internal val BYTE_ENCODER: CharArray = run {
            val bs = ArrayList<Int>()
            (33..126).forEach { bs.add(it) }       // '!'..'~'
            (161..172).forEach { bs.add(it) }      // '¡'..'¬'
            (174..255).forEach { bs.add(it) }      // '®'..'ÿ'
            val mapping = CharArray(256)
            var n = 0
            for (b in 0..255) {
                if (b in bs) {
                    mapping[b] = b.toChar()
                } else {
                    mapping[b] = (256 + n).toChar()
                    n++
                }
            }
            mapping
        }
    }
}
