package io.melan.npulab.tokenizer

import kotlinx.serialization.json.Json
import kotlinx.serialization.json.int
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import org.junit.BeforeClass
import org.junit.Test
import java.io.File
import kotlin.test.assertEquals
import kotlin.test.assertTrue

/**
 * Decode fixtures generated by HF `WhisperTokenizer` (openai/whisper-base):
 * token id sequences (with special tokens included) and the exact
 * skip-special-tokens decode. Covers Russian, mixed scripts, emoji and
 * leading-space preservation.
 */
class WhisperTokenizerTest {

    companion object {
        private lateinit var tokenizer: WhisperTokenizer

        @JvmStatic
        @BeforeClass
        fun setUp() {
            val stream = WhisperTokenizerTest::class.java
                .getResourceAsStream("/whisper/vocab.json")!!
            val f = File.createTempFile("whvocab", ".json").apply { deleteOnExit() }
            stream.use { input -> f.outputStream().use { input.copyTo(it) } }
            tokenizer = WhisperTokenizer(f)
        }
    }

    @Test
    fun `matches HF decode on all fixtures`() {
        val text = javaClass.getResourceAsStream("/whisper/decode_fixtures.json")!!
            .readBytes().decodeToString()
        val fixtures = Json.parseToJsonElement(text).jsonArray
        assertTrue(fixtures.size >= 5)
        for (fx in fixtures) {
            val ids = fx.jsonObject["ids"]!!.jsonArray.map { it.jsonPrimitive.int }
            val expected = fx.jsonObject["expected"]!!.jsonPrimitive.content
            assertEquals(expected, tokenizer.decode(ids), "ids=$ids")
        }
    }

    @Test
    fun `special tokens are skipped`() {
        // [sot, notimestamps, eot] → empty text
        assertEquals("", tokenizer.decode(listOf(50258, 50363, 50257)))
    }
}
